% Save data needed to do a bit-reproducible restart

% Include current timestep in file name
name = sprintf('restart_%08d',time.istep);

% Save data needed to specify the model setup, current state,
% and time series diagnostic data
current_time = time.t;
save(name,'grid',...
          'current_time',...
          'constants',...
          'switches',...
          'accum_force',...
          'accum',...
          'state_old',...
          'ts');